require("init-plugins")
require("core.remaps")

require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-comment")
require("plugins.neotree")
require("plugins.themes")
require("plugins.gitsigns")
require("plugins.autopairs")
require("plugins.mdpreview")
require("plugins.nvim-cmp")
require("plugins.mason")

require("core.onstartup")
